services:
 db:
  container_name: mongo_db_compose_service
  image: mongo
  volumes:
   - mongo_data:/data/db
  ports:
   - 27017:27017
  environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=123456
    - MONGO_INITDB_DATABASE=mdatabase_test
  restart: unless-stopped
  command: ["mongod", "--auth"]

volumes:
  mongo_data:
    external: false
